### PR TITLE
Decode artboard data

### PR DESCRIPTION
**Pull request by joealcorn**
Hello!

I'm trying to extract artboards as individual images. Exporting the artboard group as-is won't give a correct result because the bounds of the group are the bounds of all layers within the group, so anything outside of the artboard will also be included.

For example, exporting this artboard (using `group.as_PIL()`)

screen shot 2017-03-21 at 16 13 46

Becomes this

uncropped

Instead of this

cropped

I need this data decoded so I can get the actual artboard bounds

```python
In [1]: from psd_tools import PSDImage

In [2]: psd = PSDImage.from_stream(open('/Users/joe/Dropbox/Mockups/Artboards/Artboards-sample.psd'))
/Users/joe/marvel/psd-tools/src/psd_tools/decoder/tagged_blocks.py:57: UserWarning: Unknown tagged block (lfxs)
  warnings.warn("Unknown tagged block (%s)" % block.key)

/Users/joe/marvel/psd-tools/src/psd_tools/decoder/tagged_blocks.py:57: UserWarning: Unknown tagged block (iOpa)
  warnings.warn("Unknown tagged block (%s)" % block.key)

/Users/joe/marvel/psd-tools/src/psd_tools/decoder/linked_layer.py:82: UserWarning: skipping over undocumented additional fields
  warnings.warn('skipping over undocumented additional fields')

/Users/joe/marvel/psd-tools/src/psd_tools/decoder/tagged_blocks.py:57: UserWarning: Unknown tagged block (lnkE)
  warnings.warn("Unknown tagged block (%s)" % block.key)


In [3]: artboards = [l for l in psd.layers if 'artb' in l._tagged_blocks]

In [4]: artboards
Out[4]:
[<psd_tools.Group: u'1 - Login', layer_count=8>,
 <psd_tools.Group: u'2 - Sign Up', layer_count=10>,
 <psd_tools.Group: u'3 - Walkthrough', layer_count=5>,
 <psd_tools.Group: u'4 - Home', layer_count=19>,
 <psd_tools.Group: u'5 - Calendar', layer_count=17>,
 <psd_tools.Group: u'6 - Overview', layer_count=17>]

In [5]: artboards[0]._tagged_blocks['artb']
Out[5]:
Artboard(
 version=16,
 data=Descriptor(
  name=u'',
  classID='artboard',
  items=[('artboardRect',
    Descriptor(
     name=u'',
     classID='classFloatRect',
     items=[('Top ', Double( value=144.0)),
      ('Left', Double( value=182.0)),
      ('Btom', Double( value=1479.0)),
      ('Rght', Double( value=932.0))]))]))

```

Do you want any docs or tests? Please point me in the right direction!

Thanks!

### CODE REVIEW

**Comment by kmike** [comment]
Thanks! 
A test case would be awesome, but I can merge it as-is as well.

**Comment by joealcorn** [comment]
I've added a basic test case

**Comment by joealcorn** [comment]
Happy new year! Any update on this?

**Comment by kmike** [comment]
I'm reopening it, because it was auto-closed by unrelated commit.

**Comment by kyamagu** [comment]
@kmike Sure, will check

**Comment by kyamagu** [comment]
Okay, it seems natural to have artboards as a subclass of group that has fixed dimension. Will incorporate the fix in the next minor release

**Pull request closed without merging**
